{% set python_min = '3.9.6' %}
{% set name = "nomad-camels-driver-keysight-e5270b" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_keysight_e5270b-{{ version }}.tar.gz
  sha256: 92f53b9ce875a5f5238e812d99437720e431f7f41c06946e24e14b5c61c30ad8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pyvisa
    - pyvisa-py

test:
  imports:
    - nomad_camels_driver_keysight_e5270b
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Device driver for the Keysight E5270B Precision IV Analyzer.
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
